name: Delta CI

on:
  push:
    branches: [main]
    tags-ignore: ["v*"]
  pull_request:
    branches: [main]
  create:
    tags: ["v*"]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25"
          elixir-version: "1.14.0"
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: delta-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            delta-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
            delta-

      - run: mix deps.get
      - run: mix test

      - name: Setup docs repo
        run: git clone https://github.com/delta-documents/docs.git delta-docs-repo

      - name: Build docs if main branch or tag
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        run: mix docs

      - name: Publish docs as latest if main branch
        if: github.ref == 'refs/heads/main'
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DOCS_REPO_SSH }}
        with:
          source-directory: doc
          destination-github-username: delta-documents
          destination-repository-name: docs
          target-directory: delta/latest
          commit-message: delta ${{ github.sha }}

      - name: Publish docs as version if tag and main branch
        if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v')
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DOCS_REPO_SSH }}
        with:
          source-directory: doc
          destination-github-username: delta-documents
          destination-repository-name: docs
          target-directory: delta/latest
          commit-message: delta ${{ github.sha }} as ${{ github.ref_name }}
        
      - name: Create release if tag and main branch
        if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
